# Generated by Django 3.1.4 on 2021-02-03 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocoOrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('total_ball', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(40)])),
                ('number_time_fill', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('ball_bought', models.IntegerField()),
                ('perfume', models.CharField(default='choc-oran', max_length=35, verbose_name='Chocolat Orange')),
            ],
            options={
                'verbose_name': 'Chocolat-Orange ice cream.',
            },
        ),
        migrations.CreateModel(
            name='MintChoco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('total_ball', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(40)])),
                ('number_time_fill', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('ball_bought', models.IntegerField()),
                ('perfume', models.CharField(default='mint-choc', max_length=35, verbose_name='Mint Choco')),
            ],
            options={
                'verbose_name': 'Mint-Choco ice cream.',
            },
        ),
        migrations.CreateModel(
            name='RaspberryWhiteChocolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('total_ball', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(40)])),
                ('number_time_fill', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('ball_bought', models.IntegerField()),
                ('perfume', models.CharField(default='rasp-whit-choc', max_length=35, verbose_name='Raspberry white chocolate')),
            ],
            options={
                'verbose_name': 'Raspberry-white-chocolate ice cream.',
            },
        ),
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('total_ball', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(40)])),
                ('number_time_fill', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('ball_bought', models.IntegerField()),
                ('perfume', models.CharField(default='mapple-syrup', max_length=35, verbose_name='Maple syrup')),
            ],
            options={
                'verbose_name': 'Maple-syrup ice cream.',
            },
        ),
        migrations.CreateModel(
            name='VanillaStrawberryChocolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('total_ball', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(40)])),
                ('number_time_fill', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('ball_bought', models.IntegerField()),
                ('perfume', models.CharField(default='Vani-stra-choc', max_length=35, verbose_name='Vanilla Strawberry Chocolate')),
            ],
            options={
                'verbose_name': 'Vanilla-Strawberry-Chocolate ice cream.',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('count_ball', models.IntegerField()),
                ('code', models.CharField(blank=True, default='e9169d36663311ebbd3d001c42eea82d', max_length=255, null=True, verbose_name='Code')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('is_last', models.BooleanField(db_index=True, default=False, verbose_name='Is last')),
                ('choco_oran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_cookie_app.chocoorange', verbose_name='Chocolat orange')),
                ('mint_choco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_cookie_app.mintchoco', verbose_name='Mint choco')),
                ('raspberry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_cookie_app.raspberrywhitechocolate', verbose_name='Raspberry white chocolate')),
                ('syrup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_cookie_app.syrup', verbose_name='Maple syrup')),
                ('vanilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_cookie_app.vanillastrawberrychocolate', verbose_name='Vanilla strawberry chocolate')),
            ],
        ),
    ]
