# Generated by Django 3.1.4 on 2021-02-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_app', '0002_chocoorange_mintchoco_order_raspberrywhitechocolate_syrup_vanillastrawberrychocolate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='50ae4abe663611ebbd3d001c42eea82d', max_length=255, null=True, verbose_name='Code'),
        ),
    ]
