# Generated by Django 3.1.4 on 2021-02-10 14:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_app', '0003_auto_20210203_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user.png', storage=django.core.files.storage.FileSystemStorage(location='/media/users'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='783cfd9a6baa11eb9090001c42eea82d', max_length=255, null=True, verbose_name='Code'),
        ),
    ]
